name: portfolio-local

services:
  postgres-local:
    container_name: postgres-local
    image: postgres:17.0-alpine3.20
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
