/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface User {
  birth_date: Timestamp;
  city: string;
  country: string;
  first_name: string;
  id: Generated<string>;
  last_name: string;
  phone_number: string;
  street_address: string;
  zip_code: string;
}

export interface DB {
  user: User;
}
